/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fantasysportsleague;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author winst
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        signUpLogoLabel = new javax.swing.JLabel();
        redCrossMarkLabel = new javax.swing.JLabel();
        yMinLabel = new javax.swing.JLabel();
        phonneNumberTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordPasswordField = new javax.swing.JPasswordField();
        emailLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        favouriteTeamLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        favouriteTeamComboBox = new javax.swing.JComboBox();
        alreadyHaveAccountLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        signUpLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/Signup-logotype-V11.png"))); // NOI18N
        jPanel1.add(signUpLogoLabel);
        signUpLogoLabel.setBounds(280, 20, 310, 100);

        redCrossMarkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/red x 30.png"))); // NOI18N
        redCrossMarkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redCrossMarkLabelMouseClicked(evt);
            }
        });
        jPanel1.add(redCrossMarkLabel);
        redCrossMarkLabel.setBounds(790, 10, 30, 30);

        yMinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/min yel 30.png"))); // NOI18N
        yMinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yMinLabelMouseClicked(evt);
            }
        });
        jPanel1.add(yMinLabel);
        yMinLabel.setBounds(750, 10, 30, 30);

        phonneNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phonneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonneNumberTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(phonneNumberTextField);
        phonneNumberTextField.setBounds(400, 220, 210, 30);

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField);
        emailTextField.setBounds(400, 180, 210, 30);

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameTextField);
        nameTextField.setBounds(400, 140, 210, 30);

        confirmPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPasswordField);
        confirmPasswordField.setBounds(400, 340, 210, 30);

        passwordPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordPasswordField);
        passwordPasswordField.setBounds(400, 300, 210, 30);

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setText("   Email :");
        jPanel1.add(emailLabel);
        emailLabel.setBounds(330, 180, 60, 30);

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneNumberLabel.setText(" Phone Number :");
        jPanel1.add(phoneNumberLabel);
        phoneNumberLabel.setBounds(270, 220, 120, 30);

        favouriteTeamLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        favouriteTeamLabel.setText("Favourite Team :");
        jPanel1.add(favouriteTeamLabel);
        favouriteTeamLabel.setBounds(270, 260, 120, 30);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setText("Password :");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(310, 300, 80, 30);

        confirmPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password :");
        jPanel1.add(confirmPasswordLabel);
        confirmPasswordLabel.setBounds(250, 340, 150, 30);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("  Name :");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(330, 140, 70, 30);

        favouriteTeamComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        favouriteTeamComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Arsenal", "Manchester City", "Mumbai Indians", "Chennai Super Kings", "Kolkata Knight Riders", "West Ham United", "Norwich City" }));
        favouriteTeamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favouriteTeamComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(favouriteTeamComboBox);
        favouriteTeamComboBox.setBounds(400, 260, 210, 30);

        alreadyHaveAccountLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        alreadyHaveAccountLabel.setText("Already have an Account? Click here");
        alreadyHaveAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alreadyHaveAccountLabelMouseClicked(evt);
            }
        });
        jPanel1.add(alreadyHaveAccountLabel);
        alreadyHaveAccountLabel.setBounds(290, 450, 290, 20);

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        jPanel1.add(submitButton);
        submitButton.setBounds(330, 403, 80, 30);

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton);
        resetButton.setBounds(460, 403, 70, 30);

        backgroundLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/registrationBackground.jpg"))); // NOI18N
        jPanel1.add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 830, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phonneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonneNumberTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void passwordPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPasswordFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void favouriteTeamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favouriteTeamComboBoxActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_favouriteTeamComboBoxActionPerformed

    private void redCrossMarkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redCrossMarkLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_redCrossMarkLabelMouseClicked

    private void yMinLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMinLabelMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_yMinLabelMouseClicked

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        nameTextField.setText(null);
        emailTextField.setText(null);
        phonneNumberTextField.setText(null);
        favouriteTeamComboBox.setSelectedIndex(0);
        passwordPasswordField.setText(null);
        confirmPasswordField.setText(null);        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void alreadyHaveAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyHaveAccountLabelMouseClicked
        // TODO add your handling code here:
        LoginPage lp=new LoginPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alreadyHaveAccountLabelMouseClicked

    static String makeUserId()
    {
        int counter=0;
        try 
            {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DBMSPROJECT","cannon47061");
                Statement stat=con.createStatement();
                ResultSet rs=stat.executeQuery("select user_id from user_details order by user_id");
                //con.close();
                
                while(rs.next())
                {
                    String UserIdFromDB=rs.getString("user_id");
                    if(UserIdFromDB!=null&&!"ADMIN1".equals(UserIdFromDB))
                    {
                        
                        int xid=Integer.parseInt(UserIdFromDB);
                        if(xid>counter)
                        {
                            counter=xid;
                        }
                    }
//                    if((Integer.toString(counter)) == null ? UserIdFromDB == null : (Integer.toString(counter)).equals(UserIdFromDB))
//                    {
//                        if()
//                    }
//                    else if("ADMIN1".equals(UserIdFromDB))
//                    {
//                        
//                    }
                    
//                    else
//                    {
//                        NewId=String.valueOf(counter);
////                                Integer.toString(counter);
//                    }
                        
                }
                con.close();
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);

            }
        return String.valueOf(counter+1);
    }
    boolean checkforemail(String email)
    {
        int atflag=0,dotflag=0;
        for(int i=0;i<email.length();i++)
        {
            if(email.charAt(i)=='@')
            {
                atflag=1;
            }
            if(email.charAt(i)=='.')
            {
                dotflag=1;
            }
        }
        return !(dotflag==1&&atflag==1);
    }
    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
        String name=nameTextField.getText();
        String email=emailTextField.getText();
        String phnoS=phonneNumberTextField.getText();
        String favTeam=(String)favouriteTeamComboBox.getSelectedItem();
        String password=passwordPasswordField.getText();
        String confirmpassword=confirmPasswordField.getText();
//        long phno=0;
        
        if(name.isEmpty())
        {
            
            JOptionPane.showMessageDialog(null,"Enter your name");
        }
        else
        if(email.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter your Email");
        }
        else
            if(checkforemail(email))
        {
            JOptionPane.showMessageDialog(null,"Enter a valid Email");
        }
        else
        if(phnoS.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter your Phone Number");
        }
        else
        if(phnoS.length()!=10)
        {
            JOptionPane.showMessageDialog(null,"Enter a valid Phone Number");
        }
        else
        if(!(phnoS.matches("[0-9]*")))
        {
            JOptionPane.showMessageDialog(null,"Enter a valid Phone Number");
        }
        else
        if("--Select--".equals(favTeam))
        {
//            phno=Long.parseLong(phnoS);
            JOptionPane.showMessageDialog(null,"Please Select Your Favourite Team");
        }
        else
            if(password.isEmpty()||confirmpassword.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Enter a Password");
            }
            else
            if(password.length()<6)
            {
                JOptionPane.showMessageDialog(null,"Enter a password of minimum 6 characters");
            }
        else
        if(password == null ? confirmpassword != null : !password.equals(confirmpassword))
        {
            JOptionPane.showMessageDialog(null,"Password Does Not Match");
        }
        else
        {
            int flagIfEmailExists=0;
            try 
            {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DBMSPROJECT","cannon47061");
                Statement stat=con.createStatement();
                ResultSet rs=stat.executeQuery("select email from user_details");
                //con.close();
                while(rs.next())
                {
                    String emailFromDB=rs.getString("email");
                    if(email == null ? emailFromDB == null : email.equals(emailFromDB))
                    {
                        flagIfEmailExists=1;
                        break;
                    }
                }
                if(flagIfEmailExists==1)
                {
                    JOptionPane.showMessageDialog(null,"This Email is Aready in Use");
                }
                con.close();
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);

            }
            
            
            if(flagIfEmailExists==0)
            {
                String user_id=makeUserId();
                System.out.println("one="+user_id);
                try 
                {
                    Class.forName("oracle.jdbc.OracleDriver");
                    String url="     jdbc:oracle:thin:@localhost:1521:XE      ";
                    Connection con=DriverManager.getConnection(url.trim(),"DBMSPROJECT","cannon47061");
                    Statement stat=con.createStatement();
                    System.out.println("two="+user_id);
                    stat.executeUpdate("insert into user_details(name,password,user_id,email,phno,fav_team,admin) values('"+name+"','"+password+"','"+user_id+"','"+email+"','"+phnoS+"','"+favTeam+"',0)");
                    con.close();            
                    LoginPage lp=new LoginPage();
                    lp.setVisible(true);
                    this.dispose();
                } 
                catch (ClassNotFoundException | SQLException ex) 
                {
                    Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);

                }
                
                
                
                
                
            }
            
        }      
    }//GEN-LAST:event_submitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyHaveAccountLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JComboBox favouriteTeamComboBox;
    private javax.swing.JLabel favouriteTeamLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phonneNumberTextField;
    private javax.swing.JLabel redCrossMarkLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel signUpLogoLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel yMinLabel;
    // End of variables declaration//GEN-END:variables
}
