/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fantasysportsleague;

import javax.swing.JFrame;

/**
 *
 * @author winst
 */
public class WelcomeAndSelect extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeAndSelect
     */
    String user_id="";
    public WelcomeAndSelect() {
        initComponents();
    }
    public WelcomeAndSelect(String user_id) {
        initComponents();
        this.user_id=user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        redCloseLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        cricketLabel = new javax.swing.JLabel();
        viratLabel = new javax.swing.JLabel();
        dhoniLabel = new javax.swing.JLabel();
        rohitLabel = new javax.swing.JLabel();
        footballLabel = new javax.swing.JLabel();
        aubaLabel = new javax.swing.JLabel();
        agueroLabel = new javax.swing.JLabel();
        pogbaLabel = new javax.swing.JLabel();
        chooseYourSportLabel = new javax.swing.JLabel();
        myProfileLabel = new javax.swing.JLabel();
        logOutLabel = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        redCloseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/red x 30.png"))); // NOI18N
        redCloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redCloseLabelMouseClicked(evt);
            }
        });
        jPanel1.add(redCloseLabel);
        redCloseLabel.setBounds(790, 10, 30, 30);

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/min yel 30.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel);
        minimizeLabel.setBounds(750, 10, 30, 30);

        cricketLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cricketLabelMouseClicked(evt);
            }
        });
        jPanel1.add(cricketLabel);
        cricketLabel.setBounds(430, 200, 390, 220);

        viratLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/viratKohliPng.png"))); // NOI18N
        jPanel1.add(viratLabel);
        viratLabel.setBounds(620, 200, 190, 220);

        dhoniLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/msDhoniPng.png"))); // NOI18N
        jPanel1.add(dhoniLabel);
        dhoniLabel.setBounds(530, 200, 170, 220);

        rohitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/rohitSharmaPng.png"))); // NOI18N
        jPanel1.add(rohitLabel);
        rohitLabel.setBounds(440, 200, 180, 220);

        footballLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footballLabelMouseClicked(evt);
            }
        });
        jPanel1.add(footballLabel);
        footballLabel.setBounds(0, 200, 420, 220);

        aubaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/aubaPng.png"))); // NOI18N
        jPanel1.add(aubaLabel);
        aubaLabel.setBounds(200, 200, 200, 220);

        agueroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/agueroPng.png"))); // NOI18N
        jPanel1.add(agueroLabel);
        agueroLabel.setBounds(90, 200, 200, 220);

        pogbaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/pogbaPng.png"))); // NOI18N
        jPanel1.add(pogbaLabel);
        pogbaLabel.setBounds(0, 210, 170, 210);

        chooseYourSportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/chooseYourSportPng.png"))); // NOI18N
        jPanel1.add(chooseYourSportLabel);
        chooseYourSportLabel.setBounds(110, 60, 650, 90);

        myProfileLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        myProfileLabel.setForeground(new java.awt.Color(255, 255, 255));
        myProfileLabel.setText("My Profile");
        myProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myProfileLabelMouseClicked(evt);
            }
        });
        jPanel1.add(myProfileLabel);
        myProfileLabel.setBounds(80, 10, 70, 20);

        logOutLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logOutLabel.setText("Log Out");
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
        });
        jPanel1.add(logOutLabel);
        logOutLabel.setBounds(10, 10, 60, 20);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasysportsleague/WelcomeBackgroundNew.jpg"))); // NOI18N
        jPanel1.add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 830, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void redCloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redCloseLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_redCloseLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseClicked
        // TODO add your handling code here:
        LoginPage lp=new  LoginPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutLabelMouseClicked

    private void footballLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footballLabelMouseClicked
        // TODO add your handling code here:
        FootBallPage fbp=new FootBallPage(user_id);
        fbp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_footballLabelMouseClicked

    private void cricketLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cricketLabelMouseClicked
        // TODO add your handling code here:
        CricketPage cp=new CricketPage(user_id);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cricketLabelMouseClicked

    private void myProfileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileLabelMouseClicked
        // TODO add your handling code here:
        ProfilePage p=new ProfilePage(user_id);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myProfileLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeAndSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeAndSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeAndSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeAndSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeAndSelect().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel agueroLabel;
    private javax.swing.JLabel aubaLabel;
    private javax.swing.JLabel chooseYourSportLabel;
    private javax.swing.JLabel cricketLabel;
    private javax.swing.JLabel dhoniLabel;
    private javax.swing.JLabel footballLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel myProfileLabel;
    private javax.swing.JLabel pogbaLabel;
    private javax.swing.JLabel redCloseLabel;
    private javax.swing.JLabel rohitLabel;
    private javax.swing.JLabel viratLabel;
    // End of variables declaration//GEN-END:variables
}
